[feat] kakaoMap 기본세팅
ZZanMoa/ZZanMoa-Web pull request #3
Opened 2024-04-13 08:31 UTC by hoon-hoon

### PR Type
feat: kakaoMap 마커 표시 및 확대축소/현위치 기능

---

확대축소 기능은 카카오맵 api 에서 제공하는 기능이 있길래 와이어프레임과는 다른 형태이지만 일단 그대로 넣어뒀습니다.
현위치 기능은 따로 제공하는 기능이 없어 직접 구현 후 일단 이미지를 넣어뒀는데 이미지가 깨지고 어색한느낌이 들어 추후 아이콘으로 교체해야할 것 같습니다.
마찬가지로 카카오맵아이콘과 네이버맵아이콘도 현재 기능하고있진 않지만 이미지로 넣어뒀는데, 깨지는 것 같아 추후 수정하겠습니다.

임시데이터로부터 장소의 키워드(ex. 신창시장)를 받아 상세주소로 변환하고, 상세주소를 위도경도로 변환해 지도에 마커로 찍는 과정입니다.

2024-04-13 09:39 UTC, Choi-Jinwook requested changes
코멘트 한 번씩 확인 부탁드립니다!
또한, dev 브랜치 중간중간 pull 받으면서 작업해주세요!
오리진 레포에 접근 불가능한건 어떤건지 잘 모르겠습니다ㅠㅠ

2024-04-13 09:39 UTC, Choi-Jinwook commented on pages/PriceComparision.tsx
> +    const [map, setMap] = useState<kakao.maps.Map | null>(null);
[해당 부분](https://github.com/ZZanMoa/ZZanMoa-Web/pull/3/commits/04411b306793830770b0a24135eca0ab90145c2a#diff-90538263037e194051a5c4b57459de072e7720666d03c867f33910f96def2d81R15) 이랑 다른 점이 무엇일까요?

2024-04-13 09:39 UTC, Choi-Jinwook commented on src/shared/components/NavBar.tsx
> +};
interface와 type의 차이를 알고, 어떤 상황에는 무엇을 쓰는게 좋은지 알면 좋을 것 같습니다!
주로 단일 변수(const, let 등)에는 type, 나머지 상황에서는 interface를 사용하는것이 보편적입니다.
현재 이 부분은 컴포넌트가 받아오는 props이고, props는 기능을 추가하다 보면 늘어날 수 있기 때문에 props 부분은 interface로 관리하는 것이 일반적입니다.

또한, [해당 부분](https://github.com/ZZanMoa/ZZanMoa-Web/pull/3/commits/04411b306793830770b0a24135eca0ab90145c2a#diff-aa98fd0757d0e1741503c50cfafb7726939d19819638bbe8e030a27adfec34a3R17)에서 setState action을 넘겨주고 있는데, 이는 다른 함수를 만들어서 setState action을 상위 컴포넌트에서 관리해 주는 것이 좋습니다.

```typescript
// pages/index.tsx에서
const [activeTab, setActiveTab] = useState<Tab>('findStore');

const handleTapChange = (tabName: string) => {
  setActiveTab(tabName);
}

<Navigation onTabChange={handleTapChange} />

2024-04-13 09:39 UTC, Choi-Jinwook commented on pages/PriceComparision.tsx
> +export const PriceComparision: React.FC = () => {
`page routing`을 사용하려면 default export를 사용해야 합니다!
```suggestion
const PriceComparision = () => {

// 나머지 코드

}
export default PriceComparision
```

2024-04-13 09:39 UTC, Choi-Jinwook commented on src/shared/components/map/Marker.tsx
[리액트용 카카오맵 문서](https://react-kakao-maps-sdk.jaeseokim.dev/docs/intro)가 있습니다.
현재 파일에 사용된 방식은 아마 카카오 맵 공식 문서를 참조하신 것 같은데, 이는 바닐라JS 기준으로 작성된 것으로 알고 있습니다.
29번째 라인에서 `ReactDOM.render`는 더 이상 사용되지 않는다는 경고 문구가 존재하고, 웹 콘솔 창에서도 같은 에러가 발생하고 있습니다. 확인 부탁드립니다!

2024-04-14 05:15 UTC, hoon-hoon commented on pages/PriceComparision.tsx
> +    const [map, setMap] = useState<kakao.maps.Map | null>(null);
앗 파일 나누는 과정에서 헷갈린것같습니다 수정하겠습니다!

2024-04-14 05:15 UTC, hoon-hoon commented on pages/PriceComparision.tsx
> +export const PriceComparision: React.FC = () => {
감사합니다!

2024-04-15 03:16 UTC, hoon-hoon commented on src/shared/components/map/Marker.tsx
감사합니다 수정 완료하였습니다!

2024-04-15 06:03 UTC, Choi-Jinwook approved these changes
확인했습니다! LGTM

머지하고 디자인 부분 약간 수정하도록 하겠습니다!

2024-04-15 06:04 UTC, merged