[feat] AI리뷰 모달창 구현
ZZanMoa/ZZanMoa-Web pull request #50
Opened 2024-06-16 14:58 UTC by hoon-hoon

알뜰가게찾기 - 사이드네비게이션 부분 아코디언메뉴 추가
알뜰가게찾기 -> 시장가격비교 -> 알뜰가게찾기 이동 시 지도 로딩이 길던 오류 수정
AI 리뷰 모달창 임시 구현

2024-06-17 07:19 UTC, Choi-Jinwook requested changes
고생하셨습니다! 리뷰 한번씩만 확인 부탁드릴게요

2024-06-17 07:19 UTC, Choi-Jinwook commented on src/shared/components/Accordion.tsx
> +    const toggleAccordion = () => setIsOpen(!isOpen);
```suggestion
const toggleAccordion = () => setIsOpen(prev => !prev);
```
이전 상태를 그대로 사용하고자 하면 setState에서 이전 상태를 가져오는 것이 좋습니다!

2024-06-17 07:19 UTC, Choi-Jinwook commented on src/shared/components/Accordion.tsx
> +    title: string,
```suggestion
    title: string;
```

2024-06-17 07:44 UTC, hoon-hoon commented on src/shared/components/Accordion.tsx
> +    const toggleAccordion = () => setIsOpen(!isOpen);
아하 좋네요 감사합니다!!

2024-06-18 14:46 UTC, Choi-Jinwook reviewed
커스텀 훅 사용한 부분 굉장히 좋은 것 같아요!! 코멘트 사소한 부분에 대한건데 한번씩 확인 부탁드립니다!
`prettier` 사용은 강력 추천드립니다! 이건 나중에 협업하는 사람들의 성향에 따라 사소한 부분이 아닐 수 있어요!

2024-06-18 14:46 UTC, Choi-Jinwook commented on src/shared/components/map/UseReviewModal.tsx
> +  const [isModalOpen, setIsModalOpen] = useState(false);
사소한 부분이지만 initial value가 존재하는 경우에 대한 타입 정의를 통일해주는 것이 좋습니다!
개인적으로는 initial value가 존재하는 경우 타입 정의를 굳이 하지 않는 쪽을 선호합니다!
```suggestion
  const [storeName, setStoreName] = useState("");
  const [isModalOpen, setIsModalOpen] = useState(false);
  // 또는
  const [storeName, setStoreName] = useState<string>("");
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
```

2024-06-18 14:46 UTC, Choi-Jinwook commented on src/shared/components/map/ReviewModal.tsx
>                          <img src="/images/aiImage.svg" alt="리뷰 아이콘" style={{ width: 43, height: 38 }} />
prettier 사용을 추천드립니다! intend가 들쭉날쭉하고, 따옴표도 single, double quote가 섞여 있습니다. prettier 세팅을 한 번 해 두면 이런 일을 줄일 수 있고, 남이 코드를 읽을 때는 물론이고 내 자신이 코드를 나중에 볼 때 편해집니다!

2024-06-19 19:38 UTC, hoon-hoon commented on src/shared/components/map/ReviewModal.tsx
>                          <img src="/images/aiImage.svg" alt="리뷰 아이콘" style={{ width: 43, height: 38 }} />
아이고 써야지써야지 매번 생각했는데.. 감사드립니다 앞으로는 적용할게요!

2024-06-19 19:38 UTC, hoon-hoon commented on src/shared/components/map/UseReviewModal.tsx
> +  const [isModalOpen, setIsModalOpen] = useState(false);
아하 감사합니다!

2024-06-20 04:06 UTC, merged